name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t izygabs/hrapp-server .
      - name: Publish Image to docker hub
        run: Docker push izygabs/hrapp-server:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull izygabs/hrapp-server:latest
      - name: Remove existing container if exists
        run: docker rm -f hrapp-server-container || true
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name hrapp-server-container -e MONGO_PASSWORD=`${{ secrets.MONGO_PASSWORD }}` izygabs/hrapp-server
